### ISSUE TITLE
Watcher - Accept  nameless pods

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst-watcher#5]
Allow the following yaml to return any pods of the namespace that match the labels as match. USed for deployments and other complex types. 
```yaml
    exit: 0
    timeout: 300
    pods:
      - namespace:  atlantis
        phase: Running      
        labels:
          app: atlantis
```

For example:
```bash 
Name:             atlantis-0
Namespace:        atlantis
Priority:         0
Service Account:  atlantis
Node:             k3d-kubefirst-server-0/172.30.0.3
Start Time:       Sat, 17 Dec 2022 13:37:52 -0300
Labels:           app=atlantis
                  controller-revision-hash=atlantis-77488dff85
                  release=atlantis
                  statefulset.kubernetes.io/pod-name=atlantis-0
Annotations:      <none>
Status:           Running
...
```
