### ISSUE TITLE
Watcher - Add support to statefulset type

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst-watcher#6]
- [ ] Add support to statefulsets 

```yaml 
    exit: 0
    timeout: 300
    statefulsets:
      - namespace:  vault
        name: vault
        replicas: 1 # (current state)
        labels:
          app.kubernetes.io/instance: vault
```

It should match:
```bash
kubectl  --kubeconfig ~/k3dconfig describe statefulset -n vault vault
Name:               vault
Namespace:          vault
CreationTimestamp:  Sat, 17 Dec 2022 13:37:34 -0300
Selector:           app.kubernetes.io/instance=vault,app.kubernetes.io/name=vault,component=server
Labels:             app.kubernetes.io/instance=vault
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=vault
                    argocd.argoproj.io/instance=vault
Annotations:        <none>
Replicas:           1 desired | 1 total
Update Strategy:    OnDelete
Pods Status:        1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app.kubernetes.io/instance=vault
                    app.kubernetes.io/name=vault
                    component=server
                    helm.sh/chart=vault-0.22.0
```
