### ISSUE TITLE
Watcher - Add support to Deployments type

### ISSUE THREAD

**Issue by 6za** [kubefirst/kubefirst-watcher#7]
- [ ] Add support to deployments 

```yaml 
    exit: 0
    timeout: 300
    deployments:
      - namespace:  github-runner
        name: actions-runner-contoller-actions-runner-controller
        replicas: 1 # (current state)
        ready: true # (unavailable = 0 and available == desired) Optional
        labels:
          app.kubernetes.io/instance=actions-runner-contoller
```

It should match:
```bash
kubectl  --kubeconfig ~/k3dconfig describe deployments  -n github-runner   actions-runner-contoller-actions-runner-controller
Name:                   actions-runner-contoller-actions-runner-controller
Namespace:              github-runner
CreationTimestamp:      Sat, 17 Dec 2022 13:37:34 -0300
Labels:                 app.kubernetes.io/instance=actions-runner-contoller
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=actions-runner-controller
                        app.kubernetes.io/version=0.25.2
                        argocd.argoproj.io/instance=actions-runner-contoller
                        helm.sh/chart=actions-runner-controller-0.20.2
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app.kubernetes.io/instance=actions-runner-contoller,app.kubernetes.io/name=actions-runner-controller
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/instance=actions-runner-contoller
                    app.kubernetes.io/name=actions-runner-controller
  Service Account:  actions-runner-contoller-actions-runner-controller
```
